import miniz = libminiz%lib{miniz}

libue{fuzz_main}: c{fuzz_main}

for x: c{* -fuzz_main}
{
  n = $name($x)
  ./: exe{$n}: $x $miniz libue{fuzz_main}
}

./: exe{miniz_tester}: {hxx cxx}{timer} cxx{miniz_tester} $miniz
